# Generated by Django 5.2.1 on 2025-06-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_name_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'ادمین',
                'verbose_name_plural': 'ادمین\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='SuperAdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'سوپر ادمین',
                'verbose_name_plural': 'سوپر ادمین\u200cها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر ها'},
        ),
    ]
