# Generated by Django 5.2.1 on 2025-06-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminuser_superadminuser_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
