# Generated by Django 5.2.1 on 2025-06-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_telegram_user_whatapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='whatapp',
            new_name='whatsapp',
        ),
    ]
