# Generated by Django 5.2.1 on 2025-06-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_whatapp_user_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('civil_engineer', 'کارشناس عمران'), ('project_manager', 'مدیر پروژه'), ('surveyor', 'نقشه\u200cبردار'), ('technical_support', 'پشتیبانی فنی'), ('other', 'سایر')], max_length=50, null=True, verbose_name='نقش'),
        ),
    ]
