# Generated by Django 5.2.1 on 2025-06-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0003_alter_supervisionrequest_building_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionrequest',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
