# Generated by Django 5.2.1 on 2025-06-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0004_supervisionrequest_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionrequest',
            name='property_type',
            field=models.CharField(blank=True, default='building', max_length=20, null=True),
        ),
    ]
