# Generated by Django 5.2.1 on 2025-06-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminuser_superadminuser_alter_user_options'),
        ('supervision', '0005_supervisionrequest_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisionrequest',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_supervision_requests', to='core.adminuser'),
        ),
    ]
