# Generated by Django 5.2.1 on 2025-06-11 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('survey', 'نقشه\u200cبرداری'), ('execution', 'پیاده\u200cسازی'), ('expert', 'کارشناسی'), ('registration', 'ثبت سند'), ('supervision', 'نظارت'), ('general', 'عمومی')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته'), ('auto_closed', 'بسته خودکار')], default='open', max_length=20)),
                ('reply_status', models.CharField(choices=[('waiting_for_admin', 'در انتظار پاسخ ادمین'), ('answered', 'پاسخ داده شده')], default='waiting_for_admin', max_length=20)),
                ('last_message_by', models.CharField(blank=True, choices=[('user', 'کاربر'), ('admin', 'ادمین')], max_length=10, null=True)),
                ('closed_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ticket_sessions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['surveyrequest', 'executionrequest', 'expertevaluationrequest', 'registrationrequest', 'supervisionrequest']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticketsession')),
            ],
        ),
    ]
