# Generated by Django 5.2.1 on 2025-06-04 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsession',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='ticketsession',
            name='auto_closed',
        ),
        migrations.RemoveField(
            model_name='ticketsession',
            name='last_activity_by_admin',
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_admin_ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_user_ticket_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketsession',
            name='closed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketsession',
            name='last_message_by',
            field=models.CharField(blank=True, choices=[('user', 'کاربر'), ('admin', 'ادمین')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ticketsession',
            name='reply_status',
            field=models.CharField(choices=[('waiting_for_admin', 'در انتظار پاسخ ادمین'), ('answered', 'پاسخ داده شده')], default='waiting_for_admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketsession',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('closed', 'بسته'), ('auto_closed', 'بسته خودکار')], default='open', max_length=20),
        ),
    ]
