# Generated by Django 5.2.1 on 2025-06-03 23:25

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_expertevaluationproject_status'),
        ('projects', '0003_alter_project_project_type_delete_projectattachment'),
        ('survey', '0006_alter_surveyproject_status'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='message',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='project',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='sender',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ادمین ارجاع شده'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=1, verbose_name='متن پیام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expert.expertevaluationproject', verbose_name='درخواست کارشناسی مرتبط'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='پروژه مرتبط'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.surveyproject', verbose_name='درخواست نقشه\u200cبرداری مرتبط'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='open', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject_type',
            field=models.CharField(choices=[('survey', 'نقشه\u200cبرداری'), ('expert', 'کارشناسی'), ('general', 'عمومی')], default='general', max_length=20, verbose_name='نوع موضوع'),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='replied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='پاسخ\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان تیکت'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پاسخ'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='message',
            field=models.TextField(verbose_name='متن پاسخ'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tickets.ticket', verbose_name='تیکت'),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tickets.models.ticket_attachment_upload_to, verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='تیکت')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
        ),
        migrations.CreateModel(
            name='TicketReplyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tickets.models.ticket_reply_attachment_upload_to, verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketreply', verbose_name='پاسخ')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
        ),
    ]
