# Generated by Django 5.2.1 on 2025-06-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_created_by_ticketsession_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsession',
            name='title',
            field=models.CharField(default='موضوع تست', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketsession',
            name='session_type',
            field=models.CharField(choices=[('survey', 'نقشه\u200cبرداری'), ('expert', 'کارشناسی'), ('general', 'عمومی')], max_length=20),
        ),
    ]
