# Generated by Django 5.2.1 on 2025-06-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_is_resolved_remove_ticket_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_replies/'),
        ),
    ]
