# Generated by Django 5.2.1 on 2025-06-12 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticketmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
