# Generated by Django 5.2.1 on 2025-06-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketsession_title_alter_ticketsession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessagefile',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketmessagefile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
