# Generated by Django 5.2.1 on 2025-06-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketsession_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='ticketsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'صفحه چت', 'verbose_name_plural': 'صفحات چت'},
        ),
    ]
