# Generated by Django 5.2.1 on 2025-06-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticketmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام\u200cها'},
        ),
    ]
