# Generated by Django 5.2.1 on 2025-06-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticketmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
