# Generated by Django 5.2.1 on 2025-06-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
        ('projects', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionrequest',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_requests', to='projects.project'),
        ),
    ]
