# Generated by Django 5.2.1 on 2025-06-12 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_alter_executionrequest_project'),
        ('projects', '0004_alter_project_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionrequest',
            name='owner',
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_execution_requests', to=settings.AUTH_USER_MODEL, verbose_name='ادمین تخصیص\u200cیافته'),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='location_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_request', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('incomplete', 'ناقص')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='executionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
    ]
