# Generated by Django 5.2.1 on 2025-06-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_executionrequest_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrequest',
            name='property_type',
            field=models.CharField(blank=True, default='building', max_length=20, null=True),
        ),
    ]
