# Generated by Django 5.2.1 on 2025-06-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminuser_superadminuser_alter_user_options'),
        ('execution', '0006_executionrequest_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionrequest',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_execution_requests', to='core.adminuser', verbose_name='ادمین تخصیص\u200cیافته'),
        ),
    ]
