# Generated by Django 5.2.1 on 2025-06-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_siteconfig_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='درباره ما', max_length=50)),
                ('header_description', models.TextField(blank=True, max_length=100)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='site/AboutUs')),
                ('our_story', models.TextField(blank=True)),
                ('our_story_image', models.ImageField(blank=True, null=True, upload_to='site/AboutUs')),
                ('our_team_title', models.CharField(blank=True, max_length=50)),
                ('our_team_description', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'db_table': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='درباره ما', max_length=50)),
                ('header_description', models.TextField(blank=True, max_length=100)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='site/ContactUs')),
                ('ai_title', models.CharField(blank=True, max_length=50)),
                ('ai_descriptions', models.TextField(blank=True, max_length=200)),
                ('ai_placeholder', models.TextField(blank=True, max_length=50)),
                ('ai_text', models.TextField(blank=True)),
                ('ai_request_text', models.TextField(blank=True)),
                ('contact_time', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_description', models.TextField(blank=True, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='site/homePage')),
                ('our_projects_description', models.TextField(blank=True, null=True)),
                ('complete_requests', models.IntegerField(blank=True, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('tickets', models.IntegerField(blank=True, null=True)),
                ('services_description', models.TextField(blank=True, max_length=200, null=True)),
                ('request_title', models.TextField(blank=True, max_length=100)),
                ('request_description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
    ]
