# Generated by Django 5.2.1 on 2025-06-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminuser_superadminuser_alter_user_options'),
        ('siteconfig', '0003_aboutus_contactus_homepage_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='our_team_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team', to='core.adminuser', verbose_name='ادمین'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='siteconfig.services', verbose_name='سرویس'),
            preserve_default=False,
        ),
    ]
