# Generated by Django 5.2.1 on 2025-06-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminuser_superadminuser_alter_user_options'),
        ('siteconfig', '0004_aboutus_our_team_member_homepage_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='our_team_member',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services',
        ),
        migrations.AlterModelTable(
            name='aboutus',
            table=None,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='our_team_member',
            field=models.ManyToManyField(to='core.adminuser'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=models.ManyToManyField(to='core.adminuser'),
        ),
    ]
