# Generated by Django 5.2.1 on 2025-06-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_remove_aboutus_our_team_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='services',
            field=models.ManyToManyField(to='siteconfig.services'),
        ),
    ]
