# Generated by Django 5.2.1 on 2025-06-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminuser_superadminuser_alter_user_options'),
        ('siteconfig', '0006_alter_homepage_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'صفحه اصلی', 'verbose_name_plural': 'صفحه اصلی'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='header_description',
            field=models.TextField(blank=True, max_length=100, verbose_name='توضیحات درباره ما'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/AboutUs', verbose_name='عکس درباره ما'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='header_title',
            field=models.CharField(default='درباره ما', max_length=50, verbose_name='تیتر درباره ما'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_story',
            field=models.TextField(blank=True, verbose_name='داستان ما'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_story_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/AboutUs', verbose_name='عکس داستان ما'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_team_description',
            field=models.TextField(blank=True, max_length=100, verbose_name='توضیحات تیم ما'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_team_member',
            field=models.ManyToManyField(to='core.adminuser', verbose_name='اعضای تیم ما'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_team_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='تیتر تیم ما'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='ai_descriptions',
            field=models.TextField(blank=True, max_length=200, verbose_name='توضیحات هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='ai_placeholder',
            field=models.TextField(blank=True, max_length=50, verbose_name='متن جایگزین پیشفرض'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='ai_request_text',
            field=models.TextField(blank=True, verbose_name='دستور هوش مصنوعی برای درخواست'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='ai_text',
            field=models.TextField(blank=True, verbose_name='درستور هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='ai_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='تیتر هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_time',
            field=models.TextField(blank=True, max_length=100, verbose_name='ساعت کاری'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='header_description',
            field=models.TextField(blank=True, max_length=100, verbose_name='توضیحات درباره ما'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/ContactUs', verbose_name='عکس تماس با ما'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='header_title',
            field=models.CharField(default='درباره ما', max_length=50, verbose_name='تیتر تماس با ما'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='complete_requests',
            field=models.IntegerField(blank=True, null=True, verbose_name='پروژه های تکمیل شده'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_description',
            field=models.TextField(blank=True, default=1, verbose_name='توضیحات هیدر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/homePage', verbose_name='عکس هیدر'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='our_projects_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات دستاوردهای ما'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='request_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات ثبت درخواست'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='request_title',
            field=models.TextField(blank=True, max_length=100, verbose_name='تیتر ثبت درخواست'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services',
            field=models.ManyToManyField(to='siteconfig.services', verbose_name='سرویس ها'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات خدمات ما'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tickets',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد تیکت ها'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='user',
            field=models.IntegerField(blank=True, null=True, verbose_name='کاربران فعال'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع'),
        ),
    ]
