# Generated by Django 5.2.1 on 2025-06-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0009_alter_contactus_header_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='ai_placeholder',
            field=models.TextField(blank=True, max_length=100, verbose_name='متن جایگزین پیشفرض'),
        ),
    ]
