# Generated by Django 5.2.1 on 2025-06-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0010_alter_contactus_ai_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_title',
            field=models.CharField(blank=True, default='ککتوسازه هیرکاسب', verbose_name='تایتل سایت'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_projects_title',
            field=models.CharField(blank=True, default='دستاوردهای ما', max_length=100, verbose_name='تایتل دستاورد های ما'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='request_bgColor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رنگ پس زمینه درخواست'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='request_bgImage',
            field=models.ImageField(blank=True, null=True, upload_to='site/homePage', verbose_name='عکس پس زمینه درخواست'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(blank=True, default='خدمات ما', max_length=100, verbose_name='تایتل خدمات ما'),
        ),
    ]
