# Generated by Django 5.2.1 on 2025-06-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0011_homepage_header_title_homepage_our_projects_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='request_bgImage',
            field=models.ImageField(blank=True, null=True, upload_to='site/homePage', verbose_name=' پس زمینه درخواست'),
        ),
    ]
