# Generated by Django 5.2.1 on 2025-06-24 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_alter_user_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_referrals', to='core.adminuser')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['surveyrequest', 'supervisionrequest', 'expertevaluationrequest', 'executionrequest', 'registrationrequest']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('referrer_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_referrals', to='core.adminuser')),
            ],
        ),
    ]
