# Generated by Django 5.2.1 on 2025-06-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_alter_user_national_id'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['content_type', 'object_id'], name='referrals_r_content_923d47_idx'),
        ),
    ]
