# Generated by Django 5.2.1 on 2025-06-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=20, unique=True)),
                ('app_name', models.CharField(choices=[('SURVEY', 'Survey'), ('SUPERVISION', 'Supervision'), ('EXPERT', 'Expert'), ('EXECUTION', 'Execution'), ('REGISTRATION', 'Registration')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(max_length=36)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
