# Generated by Django 5.2.1 on 2025-06-11 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True, verbose_name='مساحت (متر مربع)')),
                ('building_area', models.FloatField(blank=True, help_text="فقط در صورتی که نوع ملک 'ساختمان' باشد وارد شود.", null=True, verbose_name='مساحت بنا (متر مربع)')),
                ('main_parcel_number', models.IntegerField(blank=True, null=True, verbose_name='پلاک اصلی')),
                ('sub_parcel_number', models.IntegerField(blank=True, null=True, verbose_name='پلاک فرعی')),
                ('property_type', models.CharField(choices=[('field', 'زمین'), ('building', 'ساختمان'), ('other', 'سایر')], default='field', max_length=20, verbose_name='نوع ملک')),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('incomplete', 'ناقص')], default='pending', max_length=20)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_survey_requests', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='projects.project')),
            ],
            options={
                'verbose_name': 'نقشه برداری',
                'verbose_name_plural': 'نقشه برداری ها',
            },
        ),
    ]
