# Generated by Django 5.2.1 on 2025-05-30 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_remove_land_user_remove_project_land_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initial_request', 'درخواست اولیه'), ('field_survey', 'برداشت میدانی'), ('drawing', 'ترسیم نقشه'), ('completed', 'اتمام نقشه برداری'), ('returned_for_info', 'بازگشت برای تکمیل اطلاعات')], default='initial_request', max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_survey_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='survey_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('survey_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='survey.surveyproject')),
            ],
        ),
    ]
