# Generated by Django 5.2.1 on 2025-05-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyproject',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
