# Generated by Django 5.2.1 on 2025-05-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyproject_area_surveyproject_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattachment',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
