# Generated by Django 5.2.1 on 2025-06-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('survey', '0002_alter_surveyrequest_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_requests', to='projects.project'),
        ),
    ]
