# Generated by Django 5.2.1 on 2025-06-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options'),
        ('survey', '0003_alter_surveyrequest_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyrequest',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_requests', to='projects.project'),
        ),
    ]
