# Generated by Django 5.2.1 on 2025-05-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveyattachment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyattachment',
            name='title',
            field=models.CharField(blank=True, default='بدون عنوان', max_length=255),
        ),
    ]
