# Generated by Django 5.2.1 on 2025-05-31 10:22

import survey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_surveyattachment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyattachment',
            name='file',
            field=models.FileField(upload_to=survey.models.survey_attachment_upload_to),
        ),
    ]
