# Generated by Django 5.2.1 on 2025-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_surveyattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyproject',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('incomplete', 'ناقص')], default='pending', max_length=20),
        ),
    ]
