# Generated by Django 5.2.1 on 2025-06-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_surveyproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyproject',
            name='property_type',
            field=models.CharField(choices=[('field', 'زمینی '), ('Building', 'ساختمان'), ('other', 'سایر')], default='field', max_length=20, verbose_name='نوع ملک'),
        ),
    ]
