# Generated by Django 5.2.1 on 2025-06-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_surveyrequest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyrequest',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
