# Generated by Django 5.2.1 on 2025-06-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_surveyrequest_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyrequest',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
