# Generated by Django 5.2.1 on 2025-06-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_surveyproject_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyproject',
            name='main_parcel_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='پلاک اصلی'),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='sub_parcel_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='پلاک فرعی'),
        ),
        migrations.AlterField(
            model_name='surveyproject',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='مساحت (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='surveyproject',
            name='property_type',
            field=models.CharField(choices=[('field', 'زمین'), ('Building', 'ساختمان'), ('other', 'سایر')], default='field', max_length=20, verbose_name='نوع ملک'),
        ),
    ]
