# Generated by Django 5.2.1 on 2025-06-07 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_surveyproject_main_parcel_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyproject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
