# Generated by Django 5.2.1 on 2025-06-01 07:50

import django.db.models.deletion
import expert.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_project_type_delete_projectattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertEvaluationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50, verbose_name='نوع ملک')),
                ('main_parcel_number', models.CharField(max_length=20, verbose_name='پلاک اصلی')),
                ('sub_parcel_number', models.CharField(max_length=20, verbose_name='پلاک فرعی')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_evaluation', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='بدون عنوان', max_length=255, verbose_name='عنوان فایل')),
                ('file', models.FileField(upload_to=expert.models.expert_attachment_upload_to, verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='expert.expertevaluationproject', verbose_name='درخواست کارشناسی')),
            ],
        ),
    ]
