# Generated by Django 5.2.1 on 2025-06-11 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertEvaluationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.FloatField(blank=True, null=True, verbose_name='مساحت (متر مربع)')),
                ('property_type', models.CharField(choices=[('field', 'زمین'), ('building', 'ساختمان'), ('other', 'سایر')], default='field', max_length=20, verbose_name='نوع ملک')),
                ('main_parcel_number', models.IntegerField(verbose_name='پلاک اصلی')),
                ('sub_parcel_number', models.IntegerField(verbose_name='پلاک فرعی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('incomplete', 'ناقص')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_evaluation', to='projects.project')),
            ],
            options={
                'verbose_name': 'درخواست کارشناسی',
                'verbose_name_plural': 'درخواست\u200cهای کارشناسی',
            },
        ),
    ]
