# Generated by Django 5.2.1 on 2025-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertevaluationproject',
            name='main_parcel_number',
            field=models.IntegerField(verbose_name='پلاک اصلی'),
        ),
        migrations.AlterField(
            model_name='expertevaluationproject',
            name='sub_parcel_number',
            field=models.IntegerField(verbose_name='پلاک فرعی'),
        ),
    ]
