# Generated by Django 5.2.1 on 2025-06-12 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_alter_expertevaluationrequest_project'),
        ('projects', '0003_alter_project_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertevaluationrequest',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_expert_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertevaluationrequest',
            name='building_area',
            field=models.FloatField(blank=True, help_text="فقط در صورتی که نوع ملک 'ساختمان' باشد وارد شود.", null=True, verbose_name='مساحت بنا (متر مربع)'),
        ),
        migrations.AddField(
            model_name='expertevaluationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='expertevaluationrequest',
            name='main_parcel_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='پلاک اصلی'),
        ),
        migrations.AlterField(
            model_name='expertevaluationrequest',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_request', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='expertevaluationrequest',
            name='sub_parcel_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='پلاک فرعی'),
        ),
    ]
