# Generated by Django 5.2.1 on 2025-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_alter_expertevaluationproject_main_parcel_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertevaluationproject',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('incomplete', 'ناقص')], default='pending', max_length=20),
        ),
    ]
