# Generated by Django 5.2.1 on 2025-06-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_alter_expertevaluationproject_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertevaluationproject',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='مساحت (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='expertevaluationproject',
            name='property_type',
            field=models.CharField(choices=[('field', 'زمین'), ('Building', 'ساختمان'), ('other', 'سایر')], default='field', max_length=20, verbose_name='نوع ملک'),
        ),
    ]
