# Generated by Django 5.2.1 on 2025-06-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminuser_superadminuser_alter_user_options'),
        ('expert', '0005_expertevaluationrequest_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertevaluationrequest',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_expert_requests', to='core.adminuser'),
        ),
    ]
