# Generated by Django 5.2.1 on 2025-06-07 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_expertevaluationproject_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertevaluationproject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
