# Generated by Django 5.2.1 on 2025-06-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'پیوست', 'verbose_name_plural': 'پیوست ها'},
        ),
    ]
