# Generated by Django 5.2.1 on 2025-06-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_attachment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'پیوست', 'verbose_name_plural': 'پیوست\u200cها'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان فایل'),
        ),
    ]
