# Generated by Django 5.2.1 on 2025-06-11 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_type', models.CharField(choices=[('field', 'زمین'), ('building', 'ساختمان'), ('other', 'سایر')], default='field', max_length=20, verbose_name='نوع ملک')),
                ('ownership_status', models.CharField(choices=[('shared_deed', 'سند مشاعی'), ('normal_purchase', 'خریداری عادی')], max_length=20, verbose_name='وضعیت مالکیت')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='مساحت زمین (متر مربع)')),
                ('building_area', models.FloatField(blank=True, help_text="فقط در صورتی که نوع ملک 'ساختمان' باشد وارد شود.", null=True, verbose_name='مساحت بنا (متر مربع)')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('incomplete', 'ناقص')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_request', to='projects.project')),
            ],
            options={
                'verbose_name': 'درخواست اخذ سند',
                'verbose_name_plural': 'درخواست\u200cهای اخذ سند',
            },
        ),
    ]
