# Generated by Django 5.2.1 on 2025-06-12 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options'),
        ('registration', '0004_alter_registrationrequest_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_registration_requests', to=settings.AUTH_USER_MODEL, verbose_name='ادمین تخصیص\u200cیافته'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='main_parcel_number',
            field=models.IntegerField(blank=True, help_text='فقط برای سند مشاعی وارد شود.', null=True, verbose_name='پلاک اصلی'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='request_survey',
            field=models.BooleanField(default=False, help_text='تیک بزنید اگر نقشه UTM ندارید.', verbose_name='درخواست همزمان نقشه\u200cبرداری'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='sub_parcel_number',
            field=models.IntegerField(blank=True, help_text='فقط برای سند مشاعی وارد شود.', null=True, verbose_name='پلاک فرعی'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_request', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('incomplete', 'ناقص')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
