# Generated by Django 5.2.1 on 2025-06-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_registrationrequest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
