# Generated by Django 5.2.1 on 2025-06-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_land_user_remove_project_land_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('survey', 'نقشه\u200cبرداری'), ('deed', 'دریافت سند'), ('expert', 'کارشناس'), ('supervision', 'نظارت'), ('execution', 'اجرا')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ProjectAttachment',
        ),
    ]
