# Generated by Django 5.2.1 on 2025-06-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
    ]
